name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: sudo apt-get update; sudo apt-get install -y musl-tools
    - name: make
      run: pwd;ls;make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck || true
